<?php

if(!defined('CURRENT_ANDROID_APP_VERSION')) define('CURRENT_ANDROID_APP_VERSION', 1);
if(!defined('CURRENT_IOS_APP_VERSION')) define('CURRENT_IOS_APP_VERSION', 1);

if(!defined('ACTIVE_STATUS')) define('ACTIVE_STATUS', 1);
if(!defined('INACTIVE_STATUS')) define('INACTIVE_STATUS', 0);
//API HTTTP STATUS CODE
if(!defined('SUCCESS_CODE')) define('SUCCESS_CODE', 200);
if(!defined('BAD_FORMAT')) define('BAD_FORMAT', 400);
if(!defined('UNAUTHENTICATE')) define('UNAUTHENTICATE', 401);
if(!defined('NOT_ACCEPTABLE')) define('NOT_ACCEPTABLE', 406);

if(!defined('ANDROID')) define('ANDROID', 0);
if(!defined('IOS')) define('IOS', 1);

if(!defined('MOBILE_NUMBER_VERIFIED')) define('MOBILE_NUMBER_VERIFIED', 1);
if(!defined('MOBILE_NUMBER_NOT_VERIFIED')) define('MOBILE_NUMBER_NOT_VERIFIED', 0);

if(!defined('ADMIN_USER_TYPE')) define('ADMIN_USER_TYPE', 1);
if(!defined('NORMAL_USER_TYPE')) define('NORMAL_USER_TYPE', 2);
if(!defined('SERVICE_PROVIDER_USER_TYPE')) define('SERVICE_PROVIDER_USER_TYPE', 3);

if(!defined('PAYMENT_PENDING')) define('PAYMENT_PENDING', 0);
if(!defined('PAYMENT_SUCCESS')) define('PAYMENT_SUCCESS', 1);
if(!defined('PAYMENT_FAILED')) define('PAYMENT_FAILED', 2);

if(!defined('BOOKING_PAYMENT')) define('BOOKING_PAYMENT', 1);
if(!defined('TIP_PAYMENT')) define('TIP_PAYMENT', 2);

if(!defined('COD_PAYMENT_METHOD')) define('COD_PAYMENT_METHOD', 1);
if(!defined('ONLINE_PAYMENT_METHOD')) define('ONLINE_PAYMENT_METHOD', 2);

if(!defined('TYPE_IMAGE')) define('TYPE_IMAGE', 'I');
if(!defined('TYPE_VIDEO')) define('TYPE_VIDEO', 'V');



if(!defined('TEMPRARY_ACCOUNT_DELETE')) define('TEMPRARY_ACCOUNT_DELETE', '1');
if(!defined('PERMANTELY_ACCOUNT_DELETE')) define('PERMANTELY_ACCOUNT_DELETE', '2');

#Notification read unread
if(!defined('NOTIFICATION_READ')) define('NOTIFICATION_READ', 'READ');
if(!defined('NOTIFICATION_UN_READ')) define('NOTIFICATION_UN_READ', 'UN_READ');

# OTP Verification Types
if(!defined('SIGNUP_OTP_VERIFICATION')) define('SIGNUP_OTP_VERIFICATION', 1);
if(!defined('CHANGE_PASSWORD_OTP_VERIFICATION')) define('CHANGE_PASSWORD_OTP_VERIFICATION', 2);
if(!defined('CHANGE_EMAIL_OTP_VERIFICATION')) define('CHANGE_EMAIL_OTP_VERIFICATION', 3);


if(!defined('PROFILE_VERIFICATION_PENDING')) define('PROFILE_VERIFICATION_PENDING', 0);
if(!defined('PROFILE_VERIFICATION_APPROVE')) define('PROFILE_VERIFICATION_APPROVED', 1);
if(!defined('PROFILE_VERIFICATION_REJECT')) define('PROFILE_VERIFICATION_REJECT', 2);



if(!defined('FILE_TYPE_AUDIO')) define('FILE_TYPE_AUDIO', 1);
if(!defined('FILE_TYPE_VIDEO')) define('FILE_TYPE_VIDEO', 2);
if(!defined('FILE_TYPE_IMAGE')) define('FILE_TYPE_IMAGE', 3);
if(!defined('FILE_TYPE_OTHER')) define('FILE_TYPE_OTHER', 4);
if(!defined('FILE_TYPE_PDF')) define('FILE_TYPE_PDF', 5);


if(!defined('POST_TYPE_NORMAL')) define('POST_TYPE_NORMAL', 1);
if(!defined('POST_TYPE_STATUS_STORY')) define('POST_TYPE_STATUS_STORY', 2);
if(!defined('POST_TYPE_BOTH')) define('POST_TYPE_BOTH', 3);

if(!defined('BOOKING_TYPE_VISIT_HOMES')) define('BOOKING_TYPE_VISIT_HOMES', 1);
if(!defined('BOOKING_TYPE_ONLY_AT_WORK_PLACE')) define('BOOKING_TYPE_ONLY_AT_WORK_PLACE', 2);
if(!defined('BOOKING_TYPE_BOTH')) define('BOOKING_TYPE_BOTH', 3);


if(!defined('BOOKING_PENDING')) define('BOOKING_PENDING', 0);
if(!defined('BOOKING_ACCEPT')) define('BOOKING_ACCEPT', 1);
if(!defined('BOOKING_IN_PROGRESS')) define('BOOKING_IN_PROGRESS', 2);
if(!defined('BOOKING_COMPLETE')) define('BOOKING_COMPLETE', 3);
if(!defined('BOOKING_CANCEL')) define('BOOKING_CANCEL', 4);
if(!defined('BOOKING_REJECT')) define('BOOKING_REJECT', 5);
if(!defined('BOOKING_ARRIVED')) define('BOOKING_ARRIVED', 6);
if(!defined('CANCEL_BY_CUSTOMER')) define('CANCEL_BY_CUSTOMER', 7);

if(!defined('INDIVIDUAL_PROFILE')) define('INDIVIDUAL_PROFILE',1);
if(!defined('BUSINESS_PROFILE')) define('BUSINESS_PROFILE', 2);


if(!defined('PROFILE_NOT_SUBMIT')) define('PROFILE_NOT_SUBMIT', 0);
if(!defined('PROFILE_SUBMIT')) define('PROFILE_SUBMIT', 1);
if(!defined('PROFILE_SUCCESS')) define('PROFILE_SUCCESS', 2);
if(!defined('PROFILE_REJECT')) define('PROFILE_REJECT', 3);

if(!defined('PROFILE_NOT_SUBMIT_STATUS')) define('PROFILE_NOT_SUBMIT_STATUS', 'Not Submit');
if(!defined('PROFILE_SUBMIT_STATUS')) define('PROFILE_SUBMIT_STATUS', 'Submitted');
if(!defined('PROFILE_SUCCESS_STATUS')) define('PROFILE_SUCCESS_STATUS', 'Approved');
if(!defined('PROFILE_REJECT_STATUS')) define('PROFILE_REJECT_STATUS', 'Rejected');

if(!defined('MONDAY')) define('MONDAY', 1);
if(!defined('TUESDAY')) define('TUESDAY', 2);
if(!defined('WEDNESDAY')) define('WEDNESDAY', 3);
if(!defined('THURSDAY')) define('THURSDAY', 4);
if(!defined('FRIDAY')) define('FRIDAY', 5);
if(!defined('SATURDAY')) define('SATURDAY', 6);
if(!defined('SUNDAY')) define('SUNDAY', 7);


if(!defined('REGISTER_TYPE_BASIC')) define('REGISTER_TYPE_BASIC', 1);
if(!defined('REGISTER_TYPE_FACEBOOK')) define('REGISTER_TYPE_FACEBOOK', 2);
if(!defined('REGISTER_TYPE_GOOGLE')) define('REGISTER_TYPE_GOOGLE', 3);
if(!defined('REGISTER_TYPE_APPLE')) define('REGISTER_TYPE_APPLE', 4);

if(!defined('OPEN_SELECT_SLOTS')) define('OPEN_SELECT_SLOTS', 1);
if(!defined('OPEN_FULL_DAY')) define('OPEN_FULL_DAY', 2);
if(!defined('ON_LEAVE')) define('ON_LEAVE', 3);


if(!defined('PAST_ORDER_TAB_FILTER')) define('PAST_ORDER_TAB_FILTER', 1);
if(!defined('ONGOING_ORDER_TAB_FILTER')) define('ONGOING_ORDER_TAB_FILTER', 2);
if(!defined('TODAY_ORDER_TAB_FILTER')) define('TODAY_ORDER_TAB_FILTER', 3);
if(!defined('CURRENT_REQUEST_ORDER_TAB_FILTER')) define('CURRENT_REQUEST_ORDER_TAB_FILTER', 4);

if(!defined('NOTIFICATION_TYPE_DEFAULT')) define('NOTIFICATION_TYPE_DEFAULT', 0);
if(!defined('NOTIFICATION_TYPE_ACCOUNT_ACTIVE')) define('NOTIFICATION_TYPE_ACCOUNT_ACTIVE', 1);
if(!defined('NOTIFICATION_TYPE_ACCOUNT_DEACTIVATED')) define('NOTIFICATION_TYPE_ACCOUNT_DEACTIVATED', 2);
if(!defined('NOTIFICATION_TYPE_APPROVE_WORK_PROFILE')) define('NOTIFICATION_TYPE_APPROVE_WORK_PROFILE', 3);
if(!defined('NOTIFICATION_TYPE_REJECT_WORK_PROFILE')) define('NOTIFICATION_TYPE_REJECT_WORK_PROFILE', 4);
if(!defined('NOTIFICATION_TYPE_APPROVED_PROFILE_IDENTITY_DOCUMENT')) define('NOTIFICATION_TYPE_APPROVED_PROFILE_IDENTITY_DOCUMENT', 5);
if(!defined('NOTIFICATION_TYPE_REJECTED_PROFILE_IDENTITY_DOCUMENT')) define('NOTIFICATION_TYPE_REJECTED_PROFILE_IDENTITY_DOCUMENT', 6);
if(!defined('NOTIFICATION_TYPE_APPROVED_PROFILE_IDENTITY_VIDEO')) define('NOTIFICATION_TYPE_APPROVED_PROFILE_IDENTITY_VIDEO', 7);
if(!defined('NOTIFICATION_TYPE_REJECTED_PROFILE_IDENTITY_VIDEO')) define('NOTIFICATION_TYPE_REJECTED_PROFILE_IDENTITY_VIDEO', 8);
if(!defined('NOTIFICATION_TYPE_APPROVED_BANK_STATEMENT')) define('NOTIFICATION_TYPE_APPROVED_BANK_STATEMENT', 9);
if(!defined('NOTIFICATION_TYPE_REJECTED_BANK_STATEMENT')) define('NOTIFICATION_TYPE_REJECTED_BANK_STATEMENT', 10);
if(!defined('NOTIFICATION_TYPE_APPROVED_PERSONAL_PROFILE')) define('NOTIFICATION_TYPE_APPROVED_PERSONAL_PROFILE', 11);
if(!defined('NOTIFICATION_TYPE_REJECTED_PERSONAL_PROFILE')) define('NOTIFICATION_TYPE_REJECTED_PERSONAL_PROFILE', 12);
if(!defined('NOTIFICATION_TYPE_BOOKING_PENDING')) define('NOTIFICATION_TYPE_BOOKING_PENDING', 13);
if(!defined('NOTIFICATION_TYPE_BOOKING_ACCEPT')) define('NOTIFICATION_TYPE_BOOKING_ACCEPT', 14);
if(!defined('NOTIFICATION_TYPE_BOOKING_IN_PROGRESS')) define('NOTIFICATION_TYPE_BOOKING_IN_PROGRESS', 15);
if(!defined('NOTIFICATION_TYPE_BOOKING_COMPLETE')) define('NOTIFICATION_TYPE_BOOKING_COMPLETE', 16);
if(!defined('NOTIFICATION_TYPE_BOOKING_CANCEL')) define('NOTIFICATION_TYPE_BOOKING_CANCEL', 17);
if(!defined('NOTIFICATION_TYPE_BOOKING_REJECT')) define('NOTIFICATION_TYPE_BOOKING_REJECT', 18);
if(!defined('NOTIFICATION_TYPE_BOOKING_ARRIVED')) define('NOTIFICATION_TYPE_BOOKING_ARRIVED', 19);
if(!defined('NOTIFICATION_TYPE_SPECIALIST_ADD_BY_BUSINESS')) define('NOTIFICATION_TYPE_SPECIALIST_ADD_BY_BUSINESS', 20);
if(!defined('NOTIFICATION_TYPE_SPECIALIST_ACCEPT_BUSINESS_REQUEST')) define('NOTIFICATION_TYPE_SPECIALIST_ACCEPT_BUSINESS_REQUEST', 21);
if(!defined('NOTIFICATION_TYPE_SPECIALIST_REJECTED_BUSINESS_REQUEST')) define('NOTIFICATION_TYPE_SPECIALIST_REJECTED_BUSINESS_REQUEST', 22);
if(!defined('NOTIFICATION_TYPE_BUSINESS_REMOVE_SPECIALIST')) define('NOTIFICATION_TYPE_BUSINESS_REMOVE_SPECIALIST', 23);
if(!defined('NOTIFICATION_TYPE_SPECIALIST_LEAVE_BUSINESS')) define('NOTIFICATION_TYPE_SPECIALIST_LEAVE_BUSINESS', 24);
if(!defined('NOTIFICATION_TYPE_RATE_SERVICE')) define('NOTIFICATION_TYPE_RATE_SERVICE', 25);
if(!defined('NOTIFICATION_TYPE_RATE_CUSTOMER')) define('NOTIFICATION_TYPE_RATE_CUSTOMER', 26);
if(!defined('NOTIFICATION_TYPE_CUSTOMER_LIKE_POST')) define('NOTIFICATION_TYPE_CUSTOMER_LIKE_POST', 27);
if(!defined('NOTIFICATION_TYPE_FOLLOW_PROVIDER')) define('NOTIFICATION_TYPE_FOLLOW_PROVIDER', 28);
if(!defined('NOTIFICATION_TYPE_CUSTOMER_LIKE_COMMENT')) define('NOTIFICATION_TYPE_CUSTOMER_LIKE_COMMENT', 29);
if(!defined('NOTIFICATION_TYPE_CUSTOMER_COMMENT_ON_POST')) define('NOTIFICATION_TYPE_CUSTOMER_COMMENT_ON_POST', 30);
if(!defined('NOTIFICATION_TYPE_REPORT_POST_DELETED_BY_ADMIN')) define('NOTIFICATION_TYPE_REPORT_POST_DELETED_BY_ADMIN', 31);
if(!defined('NOTIFICATION_TYPE_REPORT_PROVIDER_BY_CUSTOMER')) define('NOTIFICATION_TYPE_REPORT_PROVIDER_BY_CUSTOMER', 32);
if(!defined('NOTIFICATION_TYPE_REPORT_USER_BY_PROVIDER')) define('NOTIFICATION_TYPE_REPORT_USER_BY_PROVIDER', 33);


if(!defined('SORT_BY_RATING_ASC')) define('SORT_BY_RATING_ASC', 1);
if(!defined('SORT_BY_RATING_DESC')) define('SORT_BY_RATING_DESC', 2);
if(!defined('SORT_BY_AVAIABLE_HOME_SERVICES')) define('SORT_BY_AVAIABLE_HOME_SERVICES', 3);
if(!defined('SORT_BY_AVAIABLE_WOK_PLACE_SERVICES')) define('SORT_BY_AVAIABLE_WOK_PLACE_SERVICES', 4);

if(!defined('PAGE_TYPE_ABOUT_US')) define('PAGE_TYPE_ABOUT_US',1);
if(!defined('PAGE_TYPE_PRIVACY_POLICY')) define('PAGE_TYPE_PRIVACY_POLICY', 2);
if(!defined('PAGE_TYPE_TERMS_AND_CONDITION')) define('PAGE_TYPE_TERMS_AND_CONDITION', 3);


//Post report type constants

if(!defined('NUDITY_OR_SEXUAL_ACTIVITY')) define('NUDITY_OR_SEXUAL_ACTIVITY', 1);
if(!defined('HATE_SPEECH_OR_SYMBOLS')) define('HATE_SPEECH_OR_SYMBOLS', 2);
if(!defined('VIOLENCE_OR_DANGEROUS_ORGANIZATIONS')) define('VIOLENCE_OR_DANGEROUS_ORGANIZATIONS', 3);
if(!defined('SALE_OF_ILLEGAL_OR_REGULATED_GOODS')) define('SALE_OF_ILLEGAL_OR_REGULATED_GOODS', 4);
if(!defined('BULLYING_OR_HARASSMENT')) define('BULLYING_OR_HARASSMENT', 5);
if(!defined('INTELLECTUAL_PROPERLY_VIOLATION')) define('INTELLECTUAL_PROPERLY_VIOLATION', 6);
if(!defined('SUICIDE_OR_SELF')) define('SUICIDE_OR_SELF', 7);
if(!defined('SCAM_OR_FRAUD')) define('SCAM_OR_FRAUD', 8);
if(!defined('FALSE_INFORMATION')) define('FALSE_INFORMATION', 9);
if(!defined('I_JUST_DONT_LIKE_IT')) define('I_JUST_DONT_LIKE_IT', 10);



